export CUDA_VISIBLE_DEVICES=0,1
# Training
autotrain llm --train --model /home2/tsadler/models/base_models/vicuna-7b --data_path /home/tsadler/data/webnlg-rf-alpaca --valid_split val --project_name /home2/tsadler/models/vicuna-7b-newins --use_peft --train_batch_size 8 --eval_batch_size 8 --num_train_epochs 1 --trainer sft --learning_rate 3e-4 --target_modules '[q_proj,k_proj,v_proj,o_proj]' --use_int4 --lora_r 16 --text_column text
autotrain llm --train --model /home2/tsadler/models/base_models/WizardLM-7b --data_path /home/tsadler/data/webnlg-rf-alpaca --valid_split val --project_name /home2/tsadler/models/WizardLM-7b-newins --use_peft --train_batch_size 8 --eval_batch_size 8 --num_train_epochs 1 --trainer sft --learning_rate 3e-4 --target_modules '[q_proj,k_proj,v_proj,o_proj]' --use_int4 --lora_r 16 --text_column text
autotrain llm --train --model /home2/tsadler/models/Llama-2-7b-hf --data_path /home/tsadler/data/webnlg-rf-llama-prompt1 --valid_split val --project_name /home2/tsadler/models/Llama-2-7b-newins-p1 --use_peft --train_batch_size 8 --eval_batch_size 8 --num_train_epochs 1 --trainer sft --learning_rate 3e-4 --target_modules '[q_proj,k_proj,v_proj,o_proj]' --use_int4 --lora_r 16 --text_column text
autotrain llm --train --model /home2/tsadler/models/Llama-2-7b-chat-hf --data_path /home/tsadler/data/webnlg-rf-llama-prompt1 --valid_split val --project_name /home2/tsadler/models/Llama-2-7b-chat-newins-p1 --use_peft --train_batch_size 8 --eval_batch_size 8 --num_train_epochs 1 --trainer sft --learning_rate 3e-4 --target_modules '[q_proj,k_proj,v_proj,o_proj]' --use_int4 --lora_r 16 --text_column text
autotrain llm --train --model /home2/tsadler/models/base_models/orca_mini_v2_7b --data_path /home/tsadler/data/webnlg-rf-alpaca --valid_split val --project_name /home2/tsadler/models/orca-mini-2-7b-newins --use_peft --train_batch_size 8 --eval_batch_size 8 --num_train_epochs 1 --trainer sft --learning_rate 3e-4 --target_modules '[q_proj,k_proj,v_proj,o_proj]' --use_int4 --lora_r 16 --text_column text

# Benchmarking
bash /home/tsadler/lingo-scripts/bench_gpu0.sh &  # Vicuna, wizard and orca
bash /home/tsadler/lingo-scripts/bench_gpu1.sh  # Llama